name: Spring App build plus deployment
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy the spring boot application
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Unit Tests
        run: mvn -B test --file pom.xml
      - name: Build application
        run: |
          mvn clean
          mvn -B package --file pom.xml
