name: Spring App build plus deployment
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy the spring boot application
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Unit Tests
        run: mvn -B test --file pom.xml
      - name: Build application
        run: |
          mvn clean
          mvn -B package --file pom.xml
      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-app:latest
      - name: Set up secret file
        env:
          DEBUG_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DEBUG_ACCESS_KEY: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo $DEBUG_USERNAME | sed 's/./& /g'
          echo $DEBUG_ACCESS_KEY | sed 's/./& /g'
      - name: Docker hub login
        uses: docker/login-action@v3
        with:
          username: $${{ secrets.DOCKER_HUB_USERNAME }}
          password: $${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push to Docker hub
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-app:latest

